apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-label
  labels:
    env: dev
    tier: frontend
spec:
  containers:
  - image: taeknical/myweb
    name: mynapp
    ports:
    - containerPort: 8080
      protocol: TCP