apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-nport
spec:
  replicas: 3
  selector:
    matchlabels:
      app: mynapp-rs-nport
  template:
    metadata:
      labels:
        app: mynapp-rs-nport
    spec:
      containers:
      - name: mynapp
        image: taeknical/myweb
        ports:
        - name: mynapp-http
          containerPort: 8080