apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress-rs
  template:
    metadata:
      labels:
        app: wordpress-rs
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
