apiVersion: v1
kind: PersistentVolume
metadata:
  name: mynapp-pv-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path:   /nfs-volume
    server: 192.168.122.11 #kube-master1