apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-liveness
spec:
  containers:
  - image: taeknical/myweb
    name: mynapp
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080
        