apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mynapp-ds
spec:
  selector:
    matchLabels:
      app: mynapp-ds
  template:
    metadata:
      labels:
        app: mynapp-ds
    spec:
      nodeSelector:
        node: development
      containers:
      - name: mynapp
        image: taeknical/myweb
        ports:
        - containerPort: 8080